# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_esfg4T1HqBJ3qu3DL06K1ZbMhiDVJcm
"""

first_name = input("first_name")
Second_name = input("Second_name")
print (f"full Name : {first_name} {Second_name}")

